# Conclusion

In this introduction, we ask nine questions, and answers are also provided in diagram form in each subsection: These charts show the structure and history of hate crimes in the United States over nearly 30 years. In this project, we only use exploratory techniques to recognize our data. However, our project still has some limitations.

The limitations are reflected in the fact that our data covers only the 30 years from 1991 to 2020, missing the first two years of George W. Bush's first term. The absence of this data is likely to have an impact on the question of which presidents have the highest average rate of hate crimes. Meanwhile, this data also lacks data after 2020. If time permits, we will continue to look for these data to have a more comprehensive and detailed understanding of the overall cognition of hate crimes in the United States.

Another limitation is that when we're looking at hate crimes, other than the average annual rate of the president, we're looking at the total number of hate crimes. This is actually a slight loss of scientific rigor. We would have had a population range for each city in our data, but these data contain a lot of NA and the population range in the data is a pretty large range, which makes it very difficult for us to calculate the rate of hate crimes among the population. So if time permits, we can find the number of people in the city each year, and then we can calculate the hate crime rate.

90% of the work of our project is on the analysis of categorical variables. As this course focuses on exploration, we have not built a model to predict the hate crime rate. Because of the kind of data we have, we do very little quantitative analysis, instead, we do more qualitative analysis. And as data scientists, we should use data to make our social environment better. However, due to the limitations of our project, we cannot give a series of suggestions on how to reduce the number of hate crimes and thus make our society safer. What we can do is we can use a graph to tell you what a hate crime is, what its manifestations are, what its composition is, and what its history is. I hope our analysis generalized this knowledge.

If we have time to continue to improve our project after the end of the course, we will find another data on the urban population each year, and it is better to find new data on hate crimes in the last two years, so as to calculate the hate crime rate of each place and build a model to predict the hate crime rate of a certain city in a certain state in the future. This kind of analysis can give us a preventive effect.

