# Data

## Sources

Our original data file `Hate_Crime.csv` is from FBI Crime data Explore (CDE) (https://crime-data-explorer.fr.cloud.gov/pages/home). According to the description provided along with the file, the data was collected through FBI’s Uniform Crime Reporting (UCR) Program. UCR is a program aimed 
```{r}
library(tidyverse)
hate = read.csv("resource/hate_crime.csv")
dim(hate)
names(hate)
```

## Cleaning / transformation


```{r}
hate_clean <- hate |>
  select(c(INCIDENT_ID, STATE_NAME, REGION_NAME, INCIDENT_DATE,
           OFFENDER_RACE, OFFENSE_NAME, BIAS_DESC)) |>
  separate_rows(BIAS_DESC, sep = ";") |>
  mutate(BIAS_DESC =
           replace(BIAS_DESC, 
                   BIAS_DESC == "Anti-Lesbian (Female)",
                   "Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)")) |>
  mutate(BIAS_DESC =
           replace(BIAS_DESC, 
                   BIAS_DESC == "Anti-Gay (Male)",
                   "Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)")) |>
  mutate(BIAS_DESC =
           replace(BIAS_DESC, 
                   BIAS_DESC == "Anti-Bisexual",
                   "Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)")) |>
  mutate(BIAS_DESC =
           replace(BIAS_DESC, 
                   BIAS_DESC == "Anti-Transgender",
                   "Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)")) |>
  separate_rows(OFFENSE_NAME, sep = ";") |>
  mutate(INCIDENT_DATE = as.Date(INCIDENT_DATE, "%d-%b-%y"))
hate_clean[hate_clean == ""] <- "Unknown"
  
```

## Missing value analysis
