# Interactive component

We use an interactive map to illustrate each state's hate crime trend from 1991 to 2020. There is a slider at the bottom of the map which can slide to choose the year user want to see. A play button next to the slider can animate the trend from the current year to 2020. A stop button is next to the play button, which can stop the animation if the user wants to dig into the current year's data. A pop-up will show the state name and hate crime count for that year by putting the cursor on a state. 

In the interactive map, we could discover that most of the hate crimes happened in California, New York, and New Jersey. Other states have relatively fewer cases and stable trends. But in 2020, almost all states had more hate crimes than in 2019. California has a unique pattern. Its yearly count quickly increased from 1991 to 2001, then went downward until 2014, and started to grow again. New York has an overall decreasing trend, while New Jersey has a generally increasing trend.

<iframe src="./d3/index.html" width="800" height="600"></iframe>
