# Proposal

## Research topic

Bigotry takes many forms in the United States, but one of the most violent and dangerous forms of expression is a hate crime. The Federal Bureau of Investigation's (FBI) Uniform Crime Reporting (UCR) Program defines a hate crime as a committed criminal offense which is motivated, in whole or in part, by the offender's bias(es).[Hate Crime FAQ] (https://s3-us-gov-west-1.amazonaws.com/cg-d4b776d0-d898-4153-90c8-8336f86bdfec/hate_crime_faqs.pdf) In the last three years, there has been more and more news about hate crime. This news expressed hate crimes in the United States in the news report surged to their highest level in 12 years.[CNN News] (https://www.cnn.com/2021/08/30/us/fbi-report-hate-crimes-rose-2020/index.html) As international students studying in the United States, we are curious about the historical trajectory, structure, and causes of hate crimes in the United States because this topic is very important to us (as it relates to our life safety). The theme of this project is to analyze the way hate crimes have been represented in the United States over the past several decades (1991-2020). It is hoped that our findings will raise awareness not only among international students, but also among the American people, of the serious issues that constitute the subject of this analysis. 

## Data availability

We downloaded our Hate_Crime.csv data set from [FBI: Crime data Explore (CDE)] (https://crime-data-explorer.fr.cloud.gov/pages/home). Our data source is very reliable because it is released by the FBI. The CDE is an interactive tool that helps law enforcement and the public uses and understands the massive amounts of crime data the FBI collects and publishes each year. The FBI's UCR Program manages the CDE and the nation's premier crime reporting system since 1929. It generates reliable information for use by law enforcement administration, operations, and management. Law enforcement agencies across the country voluntarily participate in the program. The data set collects data on various hate crimes that occurred between 1991 and 2020, and the last update date is September 26, 2022. Law enforcement agencies report hate crimes brought to their attention monthly or quarterly to the FBI either through their state UCR programs or directly, which means that the data set we selected for this project is the latest release. The Hate Crime Statistics data set provides annual statistics on the number of incidents, offenses, victims, and offenders in reported crimes that are motivated in whole, or in part, by an offender's bias against the victim's perceived social identity. Our data set is significantly large because our information is about hate crime data at the incident level. We initially poured the CSV data set directly into R as a data frame and found that it had 220k rows and 28 columns. This data is considered “large data" because each row is a point in time for each event, so there are multiple rows per year, each with its own event. Each event has a unique id, and an exact date (year, month, day), and other characteristics columns. Most of the data in this data set can be classified as qualitative because most of the data in this data set are categorical data about event characteristics (name, date, location, bias, agency) rather than quantitative data (numbers, etc.) This data set contains a large number of null values. While we will attempt to address them in our analysis, this should still be pointed out as a potential limiting factor in relation to the quality of our analysis results. Also, most of the data in this data set are very subjective. We cannot guarantee that the individuals working for the institutions are completely free of bias, nor can we guarantee that the biases of these individuals do not affect their data collection methods in any way. However, the UCR explained that because of motivation is subjective, it is sometimes difficult to know with certainty whether a crime resulted from the offender’s bias. Offender's bias is not a sufficient condition to a hate crime, and an incident was reported as a hate crime only when law enforcement confirms that there are sufficient evidences support that the crime was conducted by offender's prejudice. [FBI: Crime data Explore (CDE)] (https://crime-data-explorer.app.cloud.gov/#) The nice thing about this data set is that if we have questions about the data set, we can contact the UCR program directly to get answers. We will follow the FBI's principles in this project: Since crime is a sociological phenomenon influenced by a variety of factors, the FBI discourages ranking locations or making comparisons [UCR Statistics Their Proper Use] (https://ucr.fbi.gov/ucr-statistics-their-proper-use) as a way of measuring law enforcement effectiveness. Some of this data may not be comparable to previous years because of differing levels of participation over time.[FBI: Crime data Explore (CDE)] (https://crime-data-explorer.app.cloud.gov/#)
